# Generated by Django 4.0.6 on 2022-07-28 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_remove_player_stats_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default=models.CharField(max_length=255))),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default=models.CharField(max_length=255))),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_stages', models.PositiveSmallIntegerField(default=1)),
                ('current_stage', models.PositiveSmallIntegerField(default=1)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_joinable', models.BooleanField(default=True)),
                ('is_invitational', models.BooleanField(default=False)),
                ('bracket_type', models.CharField(choices=[('SE', 'Single elimination')], default='SE', max_length=2)),
                ('game', models.CharField(choices=[('SC2', 'StarCraft II: Legacy of the Void'), ('CS_GO', 'Counter-Strike: Global Offensive'), ('other', 'other')], default='SE', max_length=16)),
                ('hosts', models.ManyToManyField(related_name='hosted_tournaments', to='players.player')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.organizer')),
                ('teams', models.ManyToManyField(blank=True, related_name='played_tournaments', to='players.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_finished', models.BooleanField(default=False)),
                ('t1_score', models.PositiveSmallIntegerField(default=0)),
                ('t2_score', models.PositiveSmallIntegerField(default=0)),
                ('stage', models.PositiveSmallIntegerField(default=1)),
                ('team_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_t1', to='players.team')),
                ('team_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_t2', to='players.team')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
            ],
        ),
    ]
