# Generated by Django 4.0.6 on 2022-07-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='stats',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('players', models.ManyToManyField(to='players.player')),
                ('stats', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='players.stats')),
            ],
        ),
    ]
