# Generated by Django 4.0.6 on 2022-07-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_stats_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='teams', to='players.player'),
        ),
    ]
